from enum import Enum

class DepartmentEnum(Enum):
    DEFAULT = "Nao selecionado"
    UTI_PEDIATRICA = "UTI PEDIATRICA"
    UTI_ADULTO = "UTI ADULTO"
    PRONTO_SOCORRO = "PRONTO SOCORRO"
    CENTRO_CIRURGICO = "CENTRO CIRURGICO"
    AMBULATORIO = "AMBULATORIO"
